CREATE TABLE department (
	code BIGINT(20) PRIMARY KEY,
	name VARCHAR(50) NOT NULL,
	address VARCHAR(50) NOT NULL,
	city VARCHAR(50) NOT NULL,
	state CHAR(2) NOT NULL,
	board VARCHAR(15) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;